DROP TABLE IF EXISTS [dbo].[Equipment];

CREATE TABLE [dbo].[Equipment]
(
	[PLANT_ID]					BIGINT					NOT NULL,
	[EQUIPMENT_ID]				BIGINT IDENTITY(1,1)	NOT NULL,
	[Equipment Code]			NVARCHAR(50)			NOT NULL,
	[Equipment Name]			NVARCHAR(255)			NOT NULL,
	[Equipment Description]		NVARCHAR(2000)			NOT NULL,
	[EQUIPMENT_VENDOR_ID]		BIGINT					NOT NULL,
	[EQUIPMENT_ACTIVITY_ID]		BIGINT					NOT NULL,
	[EFF_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]				BIT						NOT NULL,
	[MODIFIEDDATE]				DATETIME				NOT NULL
);