DROP TABLE IF EXISTS [dbo].[Equipment Sensor];

CREATE TABLE [dbo].[Equipment Sensor]
(
	[PLANT_ID]						BIGINT					NOT NULL,
	[EQUIPMENT_ID]					BIGINT					NOT NULL,
	[EQUIPMENT_SENSOR_ID]			BIGINT IDENTITY(1,1)	NOT NULL,
	[Equipment Sensor Code]			NVARCHAR(50)			NOT NULL,
	[Equipment Sensor Name]			NVARCHAR(2255)			NOT NULL,
	[Equipment Sensor Description]	NVARCHAR(20)			NOT NULL,
	[EQUIPMENT_SENSOR_VENDOR_ID]	NVARCHAR(20)			NOT NULL,
	[EFF_DATE]						DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]						DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]					BIT						NOT NULL,
	[MODIFIEDDATE]					DATETIME				NOT NULL
);
