DROP TABLE IF EXISTS [dbo].[Material];

CREATE TABLE [dbo].[Material]
(
    [MATERIAL_ID]				BIGINT IDENTITY(1,1)	NOT NULL,
    [Material Code]				NVARCHAR(50)			NOT NULL,
    [Material Name]				NVARCHAR(255)			NOT NULL,
    [Material Description]		NVARCHAR(2000)			NOT NULL,
    [MATERIAL_TYPE_ID]			BIGINT					NOT NULL,
    [MATERIAL_VENDOR_ID]		BIGINT					NOT NULL,
 	[EFF_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]				BIT						NOT NULL,
	[MODIFIEDDATE]				DATETIME				NOT NULL
);