DROP TABLE IF EXISTS  [dbo].[Reason Type];

CREATE TABLE [dbo].[Reason Type]
(
	[REASON_TYPE_ID]			BIGINT IDENTITY(1,1)	NOT NULL,
	[Reason Type Name]			NVARCHAR(255)			NOT NULL,
	[Reason Type Description]	NVARCHAR(2000)			NOT NULL,
	[EFF_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]				BIT						NOT NULL,
	[MODIFIEDDATE]				DATETIME				NOT NULL
);