CREATE TABLE dim.Batch
(
    [BATCH_ID]  BIGINT IDENTITY(1,1) NOT NULL,
    [Batch Name] NVARCHAR(20) NOT NULL
    [Batch Code] NVARCHAR(20) NOT NULL,
    [Batch Description] NVARCHAR(20) NOT NULL,
    [Material Vendor] NVARCHAR(20) NOT NULL,
    [EFF_DATE] DATETIMEOFFSET(7) NOT NULL,
    [END_DATE] DATETIMEOFFSET(7) NOT NULL,
        [Site Code] BIT NOT NULL,

    
)