DROP TABLE IF EXISTS [dim].[Batch];

CREATE TABLE [dim].[Batch]
(
    [BATCH_ID]			BIGINT IDENTITY(1,1)	NOT NULL,
    [Batch Code]		NVARCHAR(59)			NOT NULL,
    [Batch Name]		NVARCHAR(255)			NOT NULL,
    [Batch Description] NVARCHAR(2000)			NOT NULL,
	[EFF_DATE]			DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]			DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]		BIT						NOT NULL,
	[MODIFIEDDATE]		DATETIME				NOT NULL
);
