DROP TABLE IF EXISTS [dim].[Material_Type];

CREATE TABLE [dim].[Material_Type]
(
    [MATERIAL_TYPE_ID]			BIGINT IDENTITY(1,1)	NOT NULL,
    [Material Type Code]		NVARCHAR(50)			NOT NULL,
    [Material Description]		NVARCHAR(2000)			NOT NULL,
    [MATERIAL_VENDOR_ID]		BIGINT					NOT NULL,
 	[EFF_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[END_DATE]					DATETIMEOFFSET(7)		NOT NULL,
	[IS_CURRENT]				BIT						NOT NULL  
);