ALTER TABLE [utility].[Production_Measure]      
ADD CONSTRAINT FK_Production_Measure_Specification_SPECIFICATION_KEY FOREIGN KEY (SPECIFICATION_KEY)     
    REFERENCES [Utility].[SPECIFICATION] (SPECIFICATION_KEY); 