ALTER TABLE [fact].[Summary]      
ADD CONSTRAINT FK_Summary_Production_Measure_PRODUCTION_MEASURE_KEY FOREIGN KEY (PRODUCTION_MEASURE_KEY)     
    REFERENCES [Utility].[Production_Measure] (PRODUCTION_MEASURE_KEY); 