
INSERT INTO [fact].[Stamping]
(
		  [BATCH_KEY]
		 ,[MATERIAL_KEY]
	     ,[REASON_KEY]
	     ,[SHIFT_KEY]
		 ,[TOOL_KEY]
		 ,[CALENDER_KEY]
	     ,[PRODUCTION_MEASURE_KEY]
	     ,[AUDIT_KEY]
	     ,[Process Order ID]
	     ,[Process Date start]
	     ,[Process Date End]
		 ,[Equipment Set Up Start]
	     ,[Equipment Set Up End]
		 ,[Event Stop Start]
		 ,[Event Stop End]
	     ,[Unscheduled Downtime Hour Amount]
	     ,[Scheduled Downtime Hour Amount]
	     ,[Scraps Quantity]
		 ,[Unfinshed Product Quantity]
	     ,[Finished Product Quantity]
		 ,[Internal Sample Quantity]
		 ,[External Sample Quantity]
	     ,[Euro Price Amount Per Unit]
)
SELECT	  [fact].[Stamping]
(          
		  [BATCH_KEY]
		 ,[MATERIAL_KEY]
	     ,[REASON_KEY]
	     ,[SHIFT_KEY]
		 ,[TOOL_KEY]
		 ,[CALENDER_KEY]
	     ,[PRODUCTION_MEASURE_KEY]
	     ,[AUDIT_KEY]
	     ,[Process Order ID]
	     ,[Process Date start]
	     ,[Process Date End]
		 ,[Equipment Set Up Start]
	     ,[Equipment Set Up End]
		 ,[Event Stop Start]
		 ,[Event Stop End]
	     ,[Unscheduled Downtime Hour Amount]
	     ,[Scheduled Downtime Hour Amount]
	     ,[Scraps Quantity]
		 ,[Unfinshed Product Quantity]
	     ,[Finished Product Quantity]
		 ,[Internal Sample Quantity]
		 ,[External Sample Quantity]
	     ,[Euro Price Amount Per Unit]
)
   FROM    [staging].[staging]
GO


