
INSERT INTO [fact].[Stamping]
           ([EQUIPMENT_KEY]
           ,[BATCH_KEY]
           ,[MATERIAL_KEY]
           ,[REASON_KEY]
           ,[SHIFT_KEY]
           ,[PRODUCTION_MEASURE_KEY]
           ,[Process Order ID]
           ,[Process Date start]
           ,[Process Date End]
           ,[Equipment Set Up Start]
           ,[Equipment Set Up End]
           ,[Equipment Adjustment Start]
           ,[Equipment Adjustment End]
           ,[Equipment Changeover Start]
           ,[Equipment Changeover End]
           ,[Machine Malfunction Stop Start]
           ,[Machine Malfunction stop End]
           ,[Weight Measurement Before Production]
           ,[Units Amount at Start of Production]
           ,[Weight Measurement After Production]
           ,[Units Amount at End of Production]
           ,[Euro Price Amount Per Unit])
     SELECT [fact].[Stamping]
           ([EQUIPMENT_KEY]
           ,[BATCH_KEY]
           ,[MATERIAL_KEY]
           ,[REASON_KEY]
           ,[SHIFT_KEY]
           ,[PRODUCTION_MEASURE_KEY]
           ,[Process Order ID]
           ,[Process Date start]
           ,[Process Date End]
           ,[Equipment Set Up Start]
           ,[Equipment Set Up End]
           ,[Equipment Adjustment Start]
           ,[Equipment Adjustment End]
           ,[Equipment Changeover Start]
           ,[Equipment Changeover End]
           ,[Machine Malfunction Stop Start]
           ,[Machine Malfunction stop End]
           ,[Weight Measurement Before Production]
           ,[Units Amount at Start of Production]
           ,[Weight Measurement After Production]
           ,[Units Amount at End of Production]
           ,[Euro Price Amount Per Unit])
  FROM [staging].[Dummy]
GO


