
INSERT INTO [fact].[Stamping]
           ([EQUIPMENT_KEY]
           ,[BATCH_KEY]
           ,[MATERIAL_KEY]
           ,[REASON_KEY]
           ,[SHIFT_KEY]
           ,[Process Order ID]
           ,[Process Date start]
           ,[Process Date End]
           ,[Process Hour Duration]
           ,[Equipment Set Up Start]
           ,[Equipment Set Up End]
           ,[Equipment Set up Duration]
           ,[Total Scheduled Hour Downtime]
           ,[Machine Malfunction Stop Start]
           ,[Machine Malfunction stop End]
           ,[Machine Malfuction Hour Duration]
           ,[Total Unscheduled Downtime]
           ,[Weight Measurement Before Production K]
           ,[Units Amount at Start of Production]
           ,[Weight Measurement After Production K]
           ,[Units Amount at End of Production]
           ,[Scraps Measurement K]
           ,[Units of Scraps]
           ,[Finished Good Measurement K]
           ,[Finished Units of Good]
           ,[Reworked Scraps Measurement K]
           ,[Units of Reworked Scraps])
     SELECT [EQUIPMENT_KEY]
      ,[BATCH_KEY]
      ,[MATERIAL_KEY]
      ,[REASON_KEY]
      ,[SHIFT_KEY]
      ,[Process_Order_ID]
      ,[Process_Date_start]
      ,[Process_Date_End]
      ,[Process_Hour_Duration]
      ,[Equipment_Set_Up_Start]
      ,[Equipment_Set_Up_End]
      ,[Equipment_Set_up_Duration]
      ,[Total_Scheduled_Hour_Downtime]
      ,[Machine_Malfunction_Stop_Start]
      ,[Machine_Malfunction_stop_End]
      ,[Machine_Malfuction_Hour_Duration]
      ,[Total_Unscheduled_Downtime]
      ,[Weight_Measurement_Before_Production_K]
      ,[Units_Amount_at_Start_of_Production]
      ,[Weight_Measurement_After_Production_K]
      ,[Units_Amount_at_End_of_Production]
      ,[Scraps_Measurement_K]
      ,[Units_of_Scraps]
      ,[Finished_Good_Measurement_K]
      ,[Finished_Units_of_Good]
      ,[Reworked_Scraps_Measurement_K]
      ,[Units_of_Reworked_Scraps]
  FROM [staging].[Dummy]
GO


